Repository anitab-org/anitab-org.github.io, pull requests merged in 2020-10, with the labels that each got.

#146 Coding : Developed the New To Open Source Section of Contribute Page
  src/Components/Content/index.js
  src/Components/Contribute/index.js
  src/Components/Contribute/style.js
  src/assets/Frame 1.png
  src/content/contributeIntro.json
Labels: Status: Changes Requested

#125 Add home section
  src/Components/Home/contribution/ContributionCard.js
  src/Components/Home/contribution/ContributionSection.js
  src/Components/Home/styles.js
  src/assets/contribution/code.png
  src/assets/contribution/design_community.png
  src/assets/contribution/documentation_training.png
  src/assets/contribution/project_management.png
  src/assets/contribution/research_outreach.png
  src/assets/contribution/testing.png
Labels: Category: Coding, Status: Changes Requested

#148 Update PULL_REQUEST_TEMPLATE.md and CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/CONTRIBUTING.md
Labels: Status: Needs Review
