Repository anitab-org/anitab-org.github.io, pull requests merged in 2020-07, with the labels that each got.

#87 docs: create content for Contribute Page Section
  src/contributeIntro.json
Labels: Category: Documentation/Training, Status: Needs Review

#99 Revert "Coding: Meet Our Open Source Community Part Of About Page "
  src/Components/About/MeetOurOpenSourceCommunity/Description.js
  src/Components/About/MeetOurOpenSourceCommunity/Members.js
  src/Components/About/MeetOurOpenSourceCommunity/index.js
  src/Components/About/MeetOurOpenSourceCommunity/member_profile_data.json
  src/Components/About/MeetOurOpenSourceCommunity/styles.js
Labels: Status: Needs Review

#84 content: add descriptions for each project in Projects page
  src/assets/github.png
  src/assets/zulip.png
  src/content/projects_content.js
Labels: Status: Needs Review

#76 feat: Footer implementation
  src/App.js
  src/Components/Footer/Contact.js
  src/Components/Footer/Form.js
  src/Components/Footer/Social.js
  src/Components/Footer/index.js
  src/Components/Footer/styles.js
  src/assets/linkedin-logo.png
Labels: Help Wanted, Status: Needs Review

#101 docs: updated readme setup instructions
  README.md
Labels: Status: Needs Review

#104 Content: Create descriptions for each recent program for Programs page
  src/content/events_description.json
Labels: Status: Changes Requested
