Repository anitab-org/anitab-org.github.io, pull requests merged in 2020-08, with the labels that each got.

#124 Deploy to testing GitHub pages on develop change.
  .travis.yml
  package.json
Labels: Category: Coding, Status: Needs Review, Type: Testing

#117 content: Added badges in README
  README.md
Labels: Status: Needs Review, Type: Maintenance

#103 docs: Add description for Events and Highlights
  src/assets/events_and_highlights/1.png
  src/assets/events_and_highlights/2.png
  src/assets/events_and_highlights/3.png
  src/assets/events_and_highlights/4.png
  src/content/events_and_highlights.json
Labels: Status: Needs Review

#127 docs: update zulip stream link
  README.md
Labels: Status: Ready to Merge

#132 Updated Footer Color from #101820 to #231B4E
  src/Components/Footer/styles.js
Labels: Status: Needs Review
