Repository anitab-org/anitab-org.github.io, pull requests merged in 2021-09, with the labels that each got.

#282 Add Linking to import from 'react-native'
  src/Components/Footer/Social.js
Labels: Status: Needs Testing

#235 fix: Documentation needs text formatting for better readability
  src/content/home.js
Labels: Status: Needs Review

#259 Added "Intro to Open Source" event to Events page
  src/assets/events_and_highlights/5.jpg
  src/content/events_and_highlights.js
Labels: Status: Ready to Merge

#240 feat: Introduced .editorconfig file to the project
  .editorconfig
Labels: Status: Ready to Merge
