Repository anitab-org/anitab-org.github.io, pull requests merged in 2021-10, with the labels that each got.

#332 Add pr template
  .github/CONTRIBUTING.md
Labels: Status: Ready to Merge

#319 feat: archive section added to projects page
  src/content/projects_content.js
  src/test/__snapshots__/Projects.test.js.snap
Labels: Status: Needs Testing

#318 feat: add programs and projects information to programs page
  src/Components/Programs/ProgramsTableSection/ProgramsTable.js
  src/Components/Programs/ProgramsTableSection/ProgramsTableRow.js
  src/Components/Programs/ProgramsTableSection/ProgramsTablesSection.js
  src/Components/Programs/ProgramsTableSection/styles.js
  src/Components/Programs/index.js
  src/content/programs.json
  yarn.lock
Labels: Status: Needs Review, hacktoberfest-accepted
